apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app

build:
  local: {}
  artifacts:
    - image: ghcr.io/avkosme/hugo-dev
      context: .
      docker:
        dockerfile: build/Dockerfile
    - image: ghcr.io/avkosme/hugo-dev-web
      context: .
      docker:
        dockerfile: build/Dockerfile.web
deploy:
  helm:
    releases:
    - name: helm
      artifactOverrides:
        image: ghcr.io/avkosme/hugo-dev
      chartPath: deployments/helm/app
      imageStrategy:
        helm: {}
    - name: hugo
      artifactOverrides:
        image: ghcr.io/avkosme/hugo-dev-web
      chartPath: deployments/helm/hugo
      imageStrategy:
        helm: {}
portForward:
- resourceType: deployment
  resourceName: hugo
  namespace: default
  port: 1313
  localPort: 1313
