apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app

build:
  artifacts:
    - image: ghcr.io/avkosme/hugo-dev
      context: .
      docker:
        dockerfile: build/Dockerfile
deploy:
  helm:
    releases:
    - name: helm
      artifactOverrides:
        image: ghcr.io/avkosme/hugo-dev
      chartPath: deployments/helm/app
      imageStrategy:
        helm: {}
